version: "3.7"
services:
  couchdb:
    image: couchdb:2.3.1
    networks:
      internal_net:
    depends_on:
      - database
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  charactercreator:
    image: quay.io/spivegin/charactercreator:latest
    ports:
      - "80:80"
      - "443:443"      
    depends_on:
      - couchdb
    networks:
      external_net:
      internal_net:
networks:
  internal_net:
    driver: overlay
